INSERT INTO Customers VALUES (1, 'Rahul');
INSERT INTO Customers VALUES (2, 'Priya');
INSERT INTO Customers VALUES (3, 'Amit');
INSERT INTO Customers VALUES (4, 'Sneha');
INSERT INTO Customers VALUES (5, 'Ramesh');

INSERT INTO Loans VALUES (101, 1, SYSDATE + 10);
INSERT INTO Loans VALUES (102, 2, SYSDATE + 40);
INSERT INTO Loans VALUES (103, 3, SYSDATE + 25);
INSERT INTO Loans VALUES (104, 4, SYSDATE + 5);
INSERT INTO Loans VALUES (105, 5, SYSDATE + 60);

COMMIT;